version: "3"
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/docker/nginx/log:/var/log/nginx
      - /home/ubuntu/www:/usr/share/nginx/htmle
